# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickPrint
                                 A QGIS plugin
 Quick Print plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-01-28
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Karol Chanaj
        email                : karol.chanaj3@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os, subprocess, platform
from qgis.core import *
from qgis.gui import *
from qgis.utils import iface
from qgis.PyQt.QtGui import *
from qgis.PyQt.QtCore import *
from qgis.PyQt.QtWidgets import *
from .quick_print_dialog import *

# Initialize Qt resources from file resources.py
from .resources import *


# Import the code for the dialog

class QuickPrintFormContainer:
    def __init__(self, title="Print title", scale_numeric=True, scale_linear=True, legend=True, north_arrow=True,
                 notes="", orientation=0, pageSize="A4", filePath="", customExtent=False, customExtentMode=0, preview=False):
        self.title = title
        self.scale_numeric = scale_numeric
        self.scale_linear = scale_linear
        self.legend = legend
        self.north_arrow = north_arrow
        self.notes = notes
        self.orientation = orientation
        self.pageSize = pageSize
        self.filePath = filePath
        self.customExtent = customExtent
        self.customExtentMode = customExtentMode
        self.pluginFont = ""
        self.preview=preview


class QuickPrintLayout:
    # layout, map, legend, northarrow, linearscale, numericscale, title, notes
    def __init__(self, map_parameters: QuickPrintFormContainer):
        self.map_parameters = map_parameters
        self.project = QgsProject.instance()
        self.manager = self.project.layoutManager()
        self.layout = self.create_layout("QuickPrintLayout")
        self.map_parameters.pluginFont = "MS Shell Dlg 2"
        self.pageCollection = self.layout.pageCollection()
        self.pageCollection.page(0).setPageSize(map_parameters.pageSize, map_parameters.orientation)

        self.map = self.create_map()
        self.title, self.title.bottomPoint = self.create_title()

        if self.map_parameters.notes:
            self.notes, self.notes.bottomPoint = self.create_notes()
        if self.map_parameters.legend:
            self.legend = self.create_legend()

        self.resize_map()

        if self.map_parameters.legend:
            self.setLegendPosition()
        if self.map_parameters.scale_numeric:
            self.numeric_scale = self.create_numeric_scale()
        if self.map_parameters.scale_linear:
            self.scaleBar = self.create_linear_scale()
        if self.map_parameters.north_arrow:
            self.north_arrow = self.create_north_arrow()

        export_failure = self.export()
        if self.map_parameters.preview:
            base_path = os.path.join(QgsProject.instance().homePath())
            preview_path = os.path.join(base_path, "preview.png")
        else:
            if export_failure == 0:
                iface.messageBar().pushMessage("Sukces", "Plik eksportowano pomyślnie!", level=Qgis.Success, duration=3)

        print("Done!")

    def create_layout(self, layout_name):
        print("Creating layout...")
        layout = QgsPrintLayout(self.project)
        layout.initializeDefaults()
        layout.setName(layout_name)

        # remove existing layout and add new
        layouts_list = self.manager.printLayouts()
        for lyout in layouts_list:
            if layout.name() == layout_name:
                self.manager.removeLayout(lyout)

        self.manager.addLayout(layout)
        return layout

    def create_map(self):
        print("Creating map...")
        map = QgsLayoutItemMap(self.layout)
        map.setFrameEnabled(True)
        map.setRect(20, 20, 20, 20)
        self.layout.addLayoutItem(map)
        return map

    def resize_map(self):
        #dodać sprawdzanie listy

        legendPresent = not self.map_parameters.legend
        notesPresent = not self.map_parameters.notes
        # calculating position and scale based on page size
        pageWidth = self.pageCollection.page(0).pageSize().width()
        pageHeight = self.pageCollection.page(0).pageSize().height()
        mapPositionX = pageWidth * 0.02
        if self.map_parameters.notes:
            mapPositionY = self.notes.bottomPoint + 2
            # mapPositionY = pageHeight * 0.076
            mapScaleY = ((pageHeight - (mapPositionY + 7.5)) / pageHeight) * pageHeight
        else:
            mapPositionY = self.title.bottomPoint
            # mapPositionY = notesBottomPointY
            mapScaleY = ((pageHeight - (mapPositionY + 7.5)) / pageHeight) * pageHeight
            # mapScaleY = pageHeight * 0.85
        if legendPresent:
            mapScaleX = pageWidth * 0.96
        else:
            mapScaleX = pageWidth * 0.78
            #mapScaleX = pageWidth - self.legend.sizeWithUnits().width()
        if self.map_parameters.customExtentMode == 1:
            if mapScaleX < mapScaleY:
                mapScaleY = mapScaleX
            else:
                mapScaleX = mapScaleY
        self.map.attemptMove(QgsLayoutPoint(mapPositionX, mapPositionY, QgsUnitTypes.LayoutMillimeters))
        self.map.attemptResize(QgsLayoutSize(mapScaleX, mapScaleY, QgsUnitTypes.LayoutMillimeters))
        # map.zoomToExtent(iface.mapCanvas().fullExtent())
        self.map.zoomToExtent(self.map_parameters.customExtent)
        # map.setExtent(customExtent)
        #return map

    def create_legend(self):
        print("Creating legend...")
        # creating legend
        legend = QgsLayoutItemLegend(self.layout)
        legend.setTitle("Legenda")
        legend.setLinkedMap(self.map)
        # set style
        legend.setLegendFilterByMapEnabled(1)
        legend.setStyleFont(QgsLegendStyle.Title, QFont(self.map_parameters.pluginFont, 14, 81))
        legend.setStyleFont(QgsLegendStyle.Group, QFont(self.map_parameters.pluginFont, 11, 75))
        legend.setStyleFont(QgsLegendStyle.Subgroup, QFont(self.map_parameters.pluginFont, 10, 63))
        legend.setStyleFont(QgsLegendStyle.SymbolLabel, QFont(self.map_parameters.pluginFont, 10))
        self.layout.addLayoutItem(legend)
        return legend

    def setLegendPosition(self):
        # set position
        mapPosition = self.map.positionWithUnits()
        mapSize = self.map.sizeWithUnits()
        pageSize = self.layout.pageCollection().page(0).pageSize()
        positionX = mapPosition.x() + mapSize.width() + 2.5
        positionY = pageSize.height() * 0.12
        self.legend.attemptMove(QgsLayoutPoint(positionX, positionY, QgsUnitTypes.LayoutMillimeters))
        # return legend
        pass

    def create_north_arrow(self):
        print("Adding north arrow...")
        # create arrow
        north = QgsLayoutItemPicture(self.layout)
        north.setPicturePath(":/images/north_arrows/layout_default_north_arrow.svg")
        north.setLinkedMap(self.map)
        self.layout.addLayoutItem(north)
        # set position
        mapPosition = self.map.positionWithUnits()
        mapSize = self.map.sizeWithUnits()
        pageSize = self.layout.pageCollection().page(0).pageSize()
        positionX = mapPosition.x() + mapSize.width() - 20
        positionY = mapPosition.y() + mapSize.height() - 20
        north.attemptResize(QgsLayoutSize(10, 10, QgsUnitTypes.LayoutMillimeters))
        north.attemptMove(QgsLayoutPoint(positionX, positionY, QgsUnitTypes.LayoutMillimeters))
        return north

    def create_linear_scale(self):
        print("Adding scale bar...")
        # set style
        scaleBar = QgsLayoutItemScaleBar(self.layout)
        scaleBar.setStyle('Line Ticks Middle')  # optionally modify the style
        scaleBar.setLinkedMap(self.map)  # map is an instance of QgsLayoutItemMap
        scaleBar.setFont(QFont(self.map_parameters.pluginFont, 9))
        scaleBar.setBoxContentSpace(0)
        scaleBar.setLabelBarSpace(1)
        scaleBar.setHeight(1)
        scaleBar.setSubdivisionsHeight(2)
        scaleBar.setMaximumBarWidth(60)
        scaleBar.setSegmentSizeMode(1)
        scaleBar.setSubdivisionsHeight(1)
        scaleBar.applyDefaultSize()
        self.layout.addLayoutItem(scaleBar)
        # scale
        pageSize = self.layout.pageCollection().page(0).pageSize()
        positionX = pageSize.width() * 0.03
        positionY = pageSize.height() - 7.5
        scaleBar.attemptMove(QgsLayoutPoint(positionX, positionY, QgsUnitTypes.LayoutMillimeters))
        scaleBar.attemptResize(QgsLayoutSize(69.198, 6.041, QgsUnitTypes.LayoutMillimeters))
        return scaleBar

    def create_numeric_scale(self):
        scaleText = QgsLayoutItemLabel(self.layout)
        scaleText.setText("Skala 1:" + "{:.0f}".format(self.map.scale()))
        scaleText.setFont(QFont(self.map_parameters.pluginFont, 11))
        scaleText.setReferencePoint(QgsLayoutItem.UpperMiddle)
        scaleText.adjustSizeToText()
        self.layout.addLayoutItem(scaleText)

        pageSize = self.layout.pageCollection().page(0).pageSize()
        mapSize = self.map.sizeWithUnits()
        mapPosition = self.map.positionWithUnits()
        positionX = mapPosition.x() + (mapSize.width() / 2.0)
        positionY = pageSize.height() - 7.5
        scaleText.attemptMove(QgsLayoutPoint(positionX, positionY, QgsUnitTypes.LayoutMillimeters))  # allows moving text box
        return scaleText

    def create_title(self):
        print("Adding title...")
        title = QgsLayoutItemLabel(self.layout)
        title.setText(self.map_parameters.title)
        title.setFont(QFont(self.map_parameters.pluginFont, 28))
        title.adjustSizeToText()
        self.layout.addLayoutItem(title)

        pageSize = self.layout.pageCollection().page(0).pageSize()
        positionX = pageSize.width() * 0.03
        positionY = pageSize.height() * 0.02
        title.attemptMove(QgsLayoutPoint(positionX, positionY, QgsUnitTypes.LayoutMillimeters))
        return title, positionY + title.sizeForText().height()

    def create_notes(self):
        print("Adding notes...")
        notes = QgsLayoutItemLabel(self.layout)
        notes.setText(self.map_parameters.notes)
        notes.setFont(QFont(self.map_parameters.pluginFont, 11))
        notes.adjustSizeToText()
        self.layout.addLayoutItem(notes)

        pageSize = self.layout.pageCollection().page(0).pageSize()
        positionY = self.title.bottomPoint
        positionX = pageSize.width() * 0.03
        notes.attemptMove(QgsLayoutPoint(positionX, positionY, QgsUnitTypes.LayoutMillimeters))  # allows moving text box
        return notes, positionY + notes.sizeForText().height()
        pass

    def export(self):
        print("Exporting...")
        exporter = QgsLayoutExporter(self.layout)
        fname, fileExtension = os.path.splitext(self.map_parameters.filePath)
        if self.map_parameters.preview:
            base_path = os.path.join(QgsProject.instance().homePath())
            preview_path = os.path.join(base_path, "preview.png")
            self.layout.renderContext().setDpi(75)
            exportError = exporter.exportToImage(preview_path, QgsLayoutExporter.ImageExportSettings())
        else:
            if fileExtension == ".pdf":
                exportError = exporter.exportToPdf(self.map_parameters.filePath, QgsLayoutExporter.PdfExportSettings())
            elif fileExtension == ".png" or fileExtension == ".jpg":
                exportError = exporter.exportToImage(self.map_parameters.filePath, QgsLayoutExporter.ImageExportSettings())
            elif fileExtension == ".svg":
                exportError = exporter.exportToSvg(self.map_parameters.filePath, QgsLayoutExporter.SvgExportSettings())
            else:
                print("upsi...")
                return -1
        return exportError

    def generate_map(self):
        # === EXPORT ===
        export_failure = export(layout, mapParameters.filePath, preview)
        if preview:
            base_path = os.path.join(QgsProject.instance().homePath())
            preview_path = os.path.join(base_path, "preview.png")
        else:
            if export_failure == 0:
                iface.messageBar().pushMessage("Sukces", "Plik eksportowano pomyślnie!", level=Qgis.Success, duration=3)

        print("Done!")
        pass

class QuickPrint:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QuickPrint_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Quick Print')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QuickPrint', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/quick_print/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Quick Print'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Quick Print'),
                action)
            self.iface.removeToolBarIcon(action)

    def updatePreview(self):
        base_path = os.path.join(QgsProject.instance().homePath())
        preview_path = os.path.join(base_path, "preview.png")
        scene = QGraphicsScene()
        scene.setBackgroundBrush(QColor.fromRgb(235, 235, 235));
        image = QPixmap(preview_path)
        sceneRect = self.dlg.previewBox.mapToScene(self.dlg.previewBox.rect()).boundingRect()
        image2 = image.scaled(sceneRect.width() - 5, sceneRect.height() - 5, 1, 1)
        scene.addPixmap(image2)
        self.dlg.previewBox.setScene(scene)

    def openFile(self):
        filepath = self.dlg.outputFileBox.text()
        if platform.system() == 'Darwin':  # macOS
            subprocess.call(('open', filepath))
        elif platform.system() == 'Windows':  # Windows
            os.startfile(filepath)
        else:  # linux variants
            subprocess.call(('xdg-open', filepath))
        pass

    def changeMapViewOption(self, indx):
        if indx == 1:
            self.dlg.customExtent.setCurrentIndex(1)
            self.dlg.customExtentMode.setEnabled(True)
        else:
            pass
        pass

    def enableExtentList(self, indx):
        if indx == 0:
            self.dlg.customExtentMode.setEnabled(False)
        else:
            self.dlg.customExtentMode.setEnabled(True)

    def zoomIn(self):
        self.dlg.mapCanvas.setMapTool(self.toolZoomIn)

    def zoomOut(self):
        self.dlg.mapCanvas.setMapTool(self.toolZoomOut)

    def pan(self):
        self.dlg.mapCanvas.setMapTool(self.toolPan)

    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Wybierz plik do zapisu", "wydruk",
            "Obraz (*.png *.jpg);;Dokument PDF (*.pdf);;Grafika wektorowa SVG (*.svg)")
        self.dlg.outputFileBox.setText(filename)

    def accept(self, preview=False):
        # zapis wartości
        self.dlg.tabWidget.setCurrentIndex(0)
        fileName = self.dlg.outputFileBox.text()
        if not fileName and not preview:
            iface.messageBar().pushMessage("Error", "Ścieżka do pliku nie może być pusta!", level=Qgis.Critical)
        else:
            customExtentButton = self.dlg.customExtent.currentIndex()
            if customExtentButton:
                customExtent = self.dlg.mapCanvas.extent()
            else:
                customExtent = iface.mapCanvas().fullExtent()
            customExtentMode = self.dlg.customExtentMode.currentIndex()
            titleText = self.dlg.titleBox.text()
            annotationsText = self.dlg.annotationsBox.text()
            numericScale = self.dlg.numericScaleBox.checkState()
            linearScale = self.dlg.linearScaleBox.checkState()
            legend = self.dlg.legendBox.checkState()
            northArrow = self.dlg.arrowBox.checkState()
            pageSize = self.dlg.sizeBox.currentText()
            orientation = self.dlg.orientationBox.currentIndex()  # 0 - pozioma, 1 - pionowa

            mapParameters = QuickPrintFormContainer(titleText, numericScale, linearScale, legend, northArrow,
                                                    annotationsText, orientation, pageSize, fileName, customExtent, customExtentMode, preview)
            plugin = QuickPrintLayout(mapParameters)
            #generate_map(mapParameters, preview)
            if preview:
                self.updatePreview()
            if self.dlg.openFileCheck.checkState() and not preview:
                self.openFile()

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QuickPrintDialog()
            self.dlg.acceptButtons.accepted.connect(self.accept)
            self.dlg.zoomInButton.clicked.connect(self.zoomIn)
            self.dlg.zoomOutButton.clicked.connect(self.zoomOut)
            self.dlg.panButton.clicked.connect(self.pan)
            self.dlg.outputFileButton.clicked.connect(self.select_output_file)
            self.dlg.previewButton.clicked.connect(lambda: self.accept(True))
            self.dlg.tabWidget.currentChanged.connect(self.changeMapViewOption)
            self.dlg.customExtent.currentIndexChanged.connect(self.enableExtentList)
            self.dlg.mapCanvas.setCanvasColor(Qt.white)
            # self.dlg.mapCanvas.enableAntiAliasing(True)
            # create the map tools
            self.toolPan = QgsMapToolPan(self.dlg.mapCanvas)
            # self.toolPan.setAction(self.actionPan)
            self.toolZoomIn = QgsMapToolZoom(self.dlg.mapCanvas, False)  # false = in
            # self.toolZoomIn.setAction(self.actionZoomIn)
            self.toolZoomOut = QgsMapToolZoom(self.dlg.mapCanvas, True)  # true = out
            # self.toolZoomOut.setAction(self.actionZoomOut)

        checked_layers = [layer.name() for layer in QgsProject().instance().layerTreeRoot().children() if
                          layer.isVisible()]
        # get map layer objects of checked layers by matching their names and store those in a list
        # layersToAdd = [layer for layer in QgsProject().instance().mapLayers().values() if layer.name() in checked_layers]
        layersToAdd = QgsProject().instance().mapLayers().values()
        self.dlg.mapCanvas.setLayers(layersToAdd)
        self.dlg.mapCanvas.setExtent(iface.mapCanvas().extent())
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
